#!/usr/bin/env python3
"""Accuracy sweep for packages/physmath against IEEE-double references (Python's math).

Generates a Larzscript program holding (input, expected) pairs as exact 17-digit
literals, runs it with `larzscript`, and prints the worst relative error per
function. Nothing is printed-and-reparsed, so the numbers are the true errors.
Usage: python3 tools/check_physmath.py [--emit tests/data_physmath.lz]"""
import math, random, subprocess, sys, os, json
random.seed(20260920)
from decimal import Decimal
def lit(x):
    """Shortest round-trip decimal for a double, written without an exponent (Larzscript has no e-notation)."""
    if x == 0: return "0"
    return format(Decimal(repr(float(x))), "f")
rows = {}
def add(name, xs, f, second=None):
    out = []
    for x in xs:
        try: out.append((x, f(x)))
        except (ValueError, OverflowError): pass
    rows[name] = out
U = random.uniform
add("sin",  [U(-50, 50) for _ in range(300)] + [U(-1e5, 1e5) for _ in range(100)] + [0, math.pi/6, math.pi/2, math.pi, 1e-9, -1e-9], math.sin)
add("cos",  [U(-50, 50) for _ in range(300)] + [U(-1e5, 1e5) for _ in range(100)] + [0, math.pi/3, math.pi/2, math.pi, 1e-9], math.cos)
add("tan",  [U(-1.5, 1.5) for _ in range(200)], math.tan)
add("exp",  [U(-700, 700) for _ in range(200)] + [U(-2, 2) for _ in range(200)] + [0, 1, -1, 1e-9], math.exp)
add("ln",   [10 ** U(-300, 300) for _ in range(200)] + [U(0.5, 2) for _ in range(200)] + [1, 2, 10, 1e-9, 1 + 1e-9], math.log)
add("atan", [U(-100, 100) for _ in range(200)] + [U(-1, 1) for _ in range(200)] + [1, -1, 0, 1e-9], math.atan)
add("asin", [U(-1, 1) for _ in range(300)] + [1, -1, 0, 0.5], math.asin)
add("acos", [U(-1, 1) for _ in range(300)] + [1, -1, 0, 0.5], math.acos)
add("sinh", [U(-30, 30) for _ in range(200)] + [U(-0.2, 0.2) for _ in range(100)] + [1e-9], math.sinh)
add("cosh", [U(-30, 30) for _ in range(200)], math.cosh)
add("tanh", [U(-10, 10) for _ in range(200)] + [U(-0.2, 0.2) for _ in range(100)], math.tanh)
add("sqrt_", [10 ** U(-300, 300) for _ in range(300)] + [10 ** U(-50, -30) for _ in range(100)] + [10 ** U(30, 50) for _ in range(100)] + [1, 2, 3, 4, 0.25, 1e-47, 1e-300, 1e300], math.sqrt)
add("log1p", [10 ** U(-14, 0) for _ in range(150)] + [-(10 ** U(-14, -0.01)) for _ in range(100)] + [U(0, 1000) for _ in range(100)], math.log1p)
add("atanh", [U(-1, 1) for _ in range(150)] + [10 ** U(-14, -1) for _ in range(100)] + [1 - 10 ** U(-14, -2) for _ in range(50)], math.atanh)
add("asinh", [U(-100, 100) for _ in range(150)] + [10 ** U(-14, 0) for _ in range(100)] + [10 ** U(0, 30) for _ in range(50)], math.asinh)
add("acosh", [1 + 10 ** U(-14, 0) for _ in range(150)] + [U(1, 1000) for _ in range(100)] + [10 ** U(3, 30) for _ in range(50)], math.acosh)
add("cbrt", [U(-1000, 1000) for _ in range(200)] + [10 ** U(-30, 30) for _ in range(100)], lambda x: math.copysign(abs(x) ** (1/3), x) if False else math.cbrt(x) if hasattr(math, "cbrt") else math.copysign(abs(x) ** (1/3), x))
# two-argument
pairs = [(U(-50, 50), U(-50, 50)) for _ in range(300)] + [(1, 1), (-1, 1), (1, -1), (-1, -1), (0, 1), (0, -1), (1, 0), (-1, 0)]
hy = [(10 ** U(-300, 300) * random.choice([-1, 1]), 10 ** U(-300, 300)) for _ in range(200)] + [(3, 4), (0, 5), (1e-200, 1e-200), (1e200, 1e200)]
pw = [(10 ** U(-3, 3), U(-30, 30)) for _ in range(300)]
def write(path, keep=None):
    thin = (lambda d: d if keep is None else d[::max(1, len(d) // keep)])
    with open(path, "w") as f:
        f.write("# GENERATED by tools/check_physmath.py - reference values from IEEE-double math.\n")
        for name, data in rows.items():
            data = thin(data)
            f.write("let REF_%s = [%s]\n" % (name.upper(), ", ".join("[%s, %s]" % (lit(x), lit(y)) for x, y in data)))
        f.write("let REF_ATAN2 = [%s]\n" % ", ".join("[%s, %s, %s]" % (lit(y), lit(x), lit(math.atan2(y, x))) for y, x in thin(pairs)))
        f.write("let REF_HYPOT = [%s]\n" % ", ".join("[%s, %s, %s]" % (lit(x), lit(y), lit(math.hypot(x, y))) for x, y in thin(hy)))
        f.write("let REF_POWF = [%s]\n" % ", ".join("[%s, %s, %s]" % (lit(x), lit(y), lit(x ** y)) for x, y in thin(pw) if abs(x ** y) < 1e300 and abs(x ** y) > 1e-300))
if "--emit" in sys.argv:
    write(sys.argv[sys.argv.index("--emit") + 1], keep=40); print("wrote", sys.argv[sys.argv.index("--emit") + 1]); sys.exit(0)
tmp = "/tmp/_pm_ref.lz"; write(tmp)
prog = open(tmp).read() + '''
import "physmath" as m
fn rel(a, b) { let d = abs(a - b); let s = abs(b); return s < 0.000000000000001 ? d : d / s }
fn sweep(name, table, fnc) {
  let worst = 0.0; let where_ = nil
  for row in table { let e = rel(fnc(row[0]), row[1]); if e > worst { worst = e; where_ = row[0] } }
  print(name + " n=" + str(len(table)) + " worst_rel_err=" + m.sci(worst, 2) + " at x=" + m.sig(where_ == nil ? 0 : where_, 6))
}
sweep("sin ", REF_SIN, m.sin); sweep("cos ", REF_COS, m.cos); sweep("tan ", REF_TAN, m.tan)
sweep("exp ", REF_EXP, m.exp); sweep("ln  ", REF_LN, m.ln); sweep("atan", REF_ATAN, m.atan)
sweep("asin", REF_ASIN, m.asin); sweep("acos", REF_ACOS, m.acos)
sweep("sinh", REF_SINH, m.sinh); sweep("cosh", REF_COSH, m.cosh); sweep("tanh", REF_TANH, m.tanh); sweep("cbrt", REF_CBRT, m.cbrt); sweep("log1p", REF_LOG1P, m.log1p); sweep("atanh", REF_ATANH, m.atanh); sweep("asinh", REF_ASINH, m.asinh); sweep("acosh", REF_ACOSH, m.acosh); sweep("sqrt_", REF_SQRT_, m.sqrt_)
let w = 0.0; for r in REF_ATAN2 { let e = rel(m.atan2(r[0], r[1]), r[2]); if e > w { w = e } }
print("atan2 n=" + str(len(REF_ATAN2)) + " worst_rel_err=" + m.sci(w, 2))
w = 0.0; for r in REF_HYPOT { let e = rel(m.hypot(r[0], r[1]), r[2]); if e > w { w = e } }
print("hypot n=" + str(len(REF_HYPOT)) + " worst_rel_err=" + m.sci(w, 2))
w = 0.0; for r in REF_POWF { let e = rel(m.powf(r[0], r[1]), r[2]); if e > w { w = e } }
print("powf  n=" + str(len(REF_POWF)) + " worst_rel_err=" + m.sci(w, 2))
'''
open("/tmp/_pm_run.lz", "w").write(prog)
env = dict(os.environ, LARZSCRIPT_PATH="packages")
r = subprocess.run(["larzscript", "/tmp/_pm_run.lz"], capture_output=True, text=True, env=env, timeout=600)
print(r.stdout + r.stderr)
