#!/usr/bin/env python3
"""Generate docs/API.md from the package sources: every public function, its parameters and the comment
directly above it. Documentation generated from the code cannot drift from the code."""
import os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ORDER = [("physmath", "Maths core: trigonometry, exp/ln, inverse hyperbolics, a correct sqrt, number formatting"),
         ("physconst", "Physical and astronomical constants (SI 2019, CODATA 2018, IAU 2015)"),
         ("complex", "Complex numbers"),
         ("quantum", "Quantum-circuit simulator: states, gates, measurement, circuits, entanglement"),
         ("qalgo", "Quantum algorithms: QFT, Grover, Deutsch-Jozsa, Bernstein-Vazirani, teleportation, phase estimation, CHSH, Shor"),
         ("qmech", "Textbook quantum mechanics: hydrogen, photons, de Broglie waves, box, oscillator, tunneling"),
         ("relativity", "Special and general relativity, black holes, GPS"),
         ("astro", "Stars, planets, distances and flat-LCDM cosmology")]
out = ["# API reference", "",
       "Generated by `tools/gen_api.py` from the package sources - do not edit by hand. Every function is pure unless noted; "
       "units are SI (metres, kilograms, seconds, joules, kelvin) unless a name says otherwise.", "",
       "Import with `import \"<package>\" as x` (put `packages/` on `LARZSCRIPT_PATH`). Private helpers start with `_`.", ""]
for name, blurb in ORDER:
    src = open(os.path.join(ROOT, "packages", name, "main.lz"), encoding="utf-8").read().splitlines()
    out += ["## `%s`" % name, "", blurb + ".", ""]
    # module header: leading comment block
    hdr = []
    for l in src:
        if l.startswith("#"): hdr.append(l.lstrip("#").strip("\n")[1:] if l.startswith("# ") else l.lstrip("#"))
        elif l.strip() == "" and hdr: hdr.append("")
        else: break
    text = "\n".join(hdr).strip()
    if text: out += ["```text", text, "```", ""]
    docs = []
    for i, l in enumerate(src):
        m = re.match(r"^fn ([A-Za-z][A-Za-z0-9_]*)\((.*?)\)\s*\{", l)
        if not m: continue
        j = i - 1; c = []
        while j >= 0 and src[j].startswith("#"): c.insert(0, src[j].lstrip("#").strip()); j -= 1
        docs.append((m.group(1), m.group(2), " ".join(x for x in c if x)))
    consts = [re.match(r"^let ([A-Z][A-Z0-9_]*) = ", l).group(1) for l in src if re.match(r"^let [A-Z][A-Z0-9_]* = ", l)]
    if consts and name not in ("physconst",): out += ["**Constants:** " + ", ".join("`%s`" % c for c in consts), ""]
    if name == "physconst": out += ["**Constants:** %d values; `INFO` maps each name to its unit, kind (exact / derived / measured / nominal), source and note. See the table in the source." % len(consts), ""]
    if docs:
        out += ["| Function | What it does |", "|---|---|"]
        for f, args, d in docs:
            out.append("| `%s(%s)` | %s |" % (f, args, d.replace("|", "\\|") or "-"))
        out.append("")
open(os.path.join(ROOT, "docs", "API.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print("docs/API.md:", sum(1 for l in out if l.startswith("| `")), "functions documented")
