#!/usr/bin/env python3
"""Reference data for tests/test_complex.lz from Python's cmath (independent implementation)."""
import cmath, math, random
from decimal import Decimal
random.seed(7)
def lit(x):
    return "0" if x == 0 else format(Decimal(repr(float(x))), "f")
def cl(z): return "%s, %s" % (lit(z.real), lit(z.imag))
rows = []
for _ in range(60):
    a = complex(random.uniform(-9, 9), random.uniform(-9, 9))
    b = complex(random.uniform(-9, 9), random.uniform(-9, 9))
    n = random.randint(-5, 9)
    small = complex(random.uniform(-4, 4), random.uniform(-7, 7))
    rows.append([a, b, a + b, a - b, a * b, a / b, cmath.exp(small), small, cmath.sqrt(a), cmath.log(a), a ** n if n >= 0 else (1 / a) ** (-n), n])
with open("tests/data_complex.lz", "w") as f:
    f.write("# GENERATED by tools/gen_ref_complex.py from Python's cmath - do not edit.\n")
    f.write("# row: a, b, a+b, a-b, a*b, a/b, exp(s), s, sqrt(a), ln(a), a^n, n\nlet CASES = [\n")
    f.write(",\n".join("  [[%s], [%s], [%s], [%s], [%s], [%s], [%s], [%s], [%s], [%s], [%s], %d]" % tuple(
        [cl(r[i]) for i in range(11)] + [r[11]]) for r in rows))
    f.write("\n]\n")
    f.write("let ABS_ARG = [%s]\n" % ",\n  ".join("[[%s], %s, %s]" % (cl(r[0]), lit(abs(r[0])), lit(cmath.phase(r[0]))) for r in rows[:30]))
print("wrote tests/data_complex.lz", len(rows), "cases")
